import 'package:flutter/material.dart';
import 'package:rxdart/rxdart.dart';
import 'api_executor.dart';
import 'jsonDataFile.dart';

class CountryListBloc {
  APIExecutor apiExecutor = APIExecutor();

  PublishSubject<List<Autogenerated>> _countryListObserver =
      PublishSubject<List<Autogenerated>>();
  Stream<List<Autogenerated>> get countryListStream =>
      _countryListObserver.stream;

  void getCountryList() {

    apiExecutor.fetchData().then((List<dynamic> value) {
      Countries countries = Countries(data: value);
      _countryListObserver.sink.add(countries.listOfCountries);

      //print(countries.listOfCountries.length);

    });
  }
}
