import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';
import 'package:http_request_get/second_page.dart';
//import 'package:listcountries_api/country_list_bloc.dart';
import 'jsonDataFile.dart';
import 'country_list_bloc.dart';
import 'second_page.dart';

class CountryList extends StatelessWidget {
  CountryList() {
    bloc.getCountryList();
  }
  CountryListBloc bloc = CountryListBloc();


  Countries countries;
  Autogenerated autogenerated;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Countries List"),
      ),
      body: buildCountryList(),
    );
  }

  Widget buildCountryList() {
    return StreamBuilder(
      stream: bloc.countryListStream,
      builder: (BuildContext context, AsyncSnapshot<List<Autogenerated>> data) {
        print(data);

        if (data.data == null) {
          return getLoadingWidget();
        } else {
          print(data.data);
          return listViewBuilder(data.data);
        }
      },
    );
  }

  Widget getLoadingWidget() {
    return Container(
      child: Center(child: Text("Loading..")),
    );
  }

  Widget listViewBuilder(List<Autogenerated> countriesData) {
    return ListView.builder(
      itemCount: countriesData.length,
      itemBuilder: (BuildContext context, index) {
        return InkWell(child: countryItem(countriesData[index]),
       onTap:(){
          Navigator.push(context, MaterialPageRoute(
            builder: (context) =>
                SecondPageWidget(autogenerated: countriesData[index]),));}
        );
      },


    );
  }

  Widget countryItem(Autogenerated country) {
    return Card(
      color: Colors.black12,
      elevation: 2.5,
      borderOnForeground: true,
      child: Container(
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(18),
          border: Border.all(color: Colors.purple, width: 8),
          boxShadow: [
            BoxShadow(
              color: Colors.grey[200],
              offset: const Offset(
                1.0,
                1.0,
              ),
              blurRadius: 10.0,
              spreadRadius: 2.0,
            ), //BoxShadow
            BoxShadow(
              color: Colors.white,
              offset: const Offset(0.0, 0.0),
              blurRadius: 2.0,
              spreadRadius: 1.5,
            ), //BoxShadow
          ],
        ),
        margin: EdgeInsets.all(10),
        padding: EdgeInsets.all(10),
        child: Container(
          child: Row(
            children: [
              Container(
                padding: EdgeInsets.all(19),
                child: Hero(
                  tag:country.flag ,
                  child: SvgPicture.network(
                    country.flag,
                    height: 50,
                    width: 70,
                  ),
                ),
              ),
              Expanded(
                child: Container(

                  margin: EdgeInsets.all(10),
                  child: Column(

                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      //taking very long to appear
                      Text(
                        "Name: ${country.name}",
                        style: TextStyle(

                          fontWeight: FontWeight.w800,
                          fontSize: 21,
                          color: Colors.purpleAccent,
                        ),
                      ),
                      Container(
                        child: Text(
                          "Code: ${country.alpha2Code}",
                        ),
                      ),

                      Container(child: Text("Continent: ${country.region}")),
                      Container(
                          child: Text("Currency: ${country.currencies[0].name}")),
                      Text("Language: ${country.languages[0].name}"),
                      //SizedBox(height: 50,)
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
