import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/painting.dart';
import 'package:http_request_get/jsonDataFile.dart';
import 'country_list.dart';
import 'package:flutter_svg/flutter_svg.dart';

class SecondPageWidget extends StatelessWidget {
  Countries countryDetails;
  Autogenerated autogenerated;

  SecondPageWidget({this.autogenerated});

  Widget listViewWidget(List<dynamic> borders) {
  //  print(borders);
    return ListView.builder(
      scrollDirection: Axis.vertical,
      itemCount: borders.length,
      itemBuilder: (BuildContext context, index) {
        return Cell(borders, index);
      },
    );
  }

  Widget Cell(List borders, index) {
    return Container(
      padding: EdgeInsets.all(15),
      height: 70,
      child: Text(
        borders[index],
        style: TextStyle(
            fontSize: 30, fontWeight: FontWeight.w400, color: Colors.white),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          "${autogenerated.name}",
        ),
        backgroundColor: Colors.purple,
        shadowColor: Colors.black,
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(35),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Hero(
              tag: autogenerated.flag,
              child: SvgPicture.network(
                autogenerated.flag,
                height: 170,
                width: 450,
              ),
            ),
            Card(
              elevation: 25,
              borderOnForeground: true,
              shadowColor: Colors.deepPurple[200],
              margin: EdgeInsets.only(top: 20),
              color: Colors.black,
              child: SizedBox(
                width: 480,
                height: 60,
                child: Text(
                  autogenerated.capital,
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 25,
                    fontWeight: FontWeight.w800,
                    decorationStyle: TextDecorationStyle.double,
                  ),
                ),
              ),
            ),
            VerticalDivider(
              thickness: 10,
              color: Colors.blueGrey,
            ),
            Card(
              elevation: 25,
              borderOnForeground: true,
              shadowColor: Colors.deepPurple[200],
              margin: EdgeInsets.only(top: 20),
              child: Padding(
                padding: const EdgeInsets.all(10.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      autogenerated.languages[0].name,
                      style: TextStyle(
                        fontSize: 25,
                        fontWeight: FontWeight.w800,
                        decorationStyle: TextDecorationStyle.double,
                      ),
                    ),
                    VerticalDivider(
                      thickness: 10,
                      color: Colors.blueGrey,
                    ),
                    Text(
                      autogenerated.currencies[0].name,
                      style: TextStyle(
                        fontSize: 25,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Card(
              elevation: 25,
              borderOnForeground: true,
              shadowColor: Colors.deepPurple[200],
              margin: EdgeInsets.only(top: 20),
              child: Padding(
                padding: const EdgeInsets.all(10.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      autogenerated.alpha2Code,
                      style: TextStyle(
                        fontSize: 25,
                        fontWeight: FontWeight.w800,
                        decorationStyle: TextDecorationStyle.double,
                      ),
                    ),
                    VerticalDivider(
                      thickness: 10,
                      color: Colors.blueGrey,
                    ),
                    Text(
                      autogenerated.region,
                      style: TextStyle(
                        fontSize: 25,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Card(
              elevation: 25,
              borderOnForeground: true,
              shadowColor: Colors.deepPurple[200],
              margin: EdgeInsets.only(top: 20),
              child: Padding(
                padding: const EdgeInsets.all(10.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      autogenerated.gini.toString(),
                      style: TextStyle(
                        fontSize: 25,
                        fontWeight: FontWeight.w800,
                        decorationStyle: TextDecorationStyle.double,
                      ),
                    ),
                    VerticalDivider(
                      thickness: 10,
                      color: Colors.blueGrey,
                    ),
                    Text(
                      autogenerated.population.toString(),
                      style: TextStyle(
                        fontSize: 25,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Card(
              elevation: 25,
              borderOnForeground: true,
              shadowColor: Colors.deepPurple[200],
              margin: EdgeInsets.only(top: 20),
              child: Padding(
                padding: const EdgeInsets.all(10.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      autogenerated.numericCode,
                      style: TextStyle(
                        fontSize: 25,
                        fontWeight: FontWeight.w800,
                        decorationStyle: TextDecorationStyle.double,
                      ),
                    ),
                    VerticalDivider(
                      thickness: 10,
                      color: Colors.blueGrey,
                    ),
                    Text(
                      autogenerated.nativeName,
                      style: TextStyle(
                        fontSize: 25,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Container(
                height: 700,
                width: 500,
margin: EdgeInsets.all(20),

                decoration: BoxDecoration(
                  color: Colors.pink[900],
                  border: Border.all(
                    color: Colors.black,
                    width: 5,
                  ),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: listViewWidget(autogenerated.borders)),
          ],
        ),
      ),
    );
  }
}
